knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: AppBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig #sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

parameters:
    appbundle_word_count_per_page: 15

services:
    #my.listener:
    #    class: AppBundle\EventListener\WordEventListener
    #    tags:
    #        - { name: doctrine.event_listener, event: prePersist }
    #    arguments: [@router]
    my.subscriber:
        class: AppBundle\EventListener\WordEventSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments: [@router]