<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends EntityRepository
{
    public function findWords($match = '')
    {
        $words = $this->createQueryBuilder('w')
            ->where('w.word LIKE :match')
            ->orWhere('w.explanation LIKE :match')
            ->orWhere('w.synonym LIKE :match')
            ->setParameter('match', '%' . $match . '%')
            ->orderBy('w.word', 'ASC')
            ->getQuery()
            ->getResult();

        // As "a" tags are saved in columns, we have to remove them before making search.
        foreach ($words as $i => $word) {
            $synonym = strip_tags($word->getSynonym());
            $explanation = strip_tags($word->getExplanation());

            if (stripos($word->getWord(), $match) === false
                && stripos($synonym, $match) === false
                && stripos($explanation, $match) === false) {
                unset($words[$i]);
            }
        }

        return $words;
    }

    public function getFindAllQuery()
    {
        return $this->createQueryBuilder('w')->getQuery();
    }
}
